# Generated by Django 4.2.5 on 2023-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=50, null=True)),
                ('yazar', models.CharField(blank=True, max_length=40, null=True)),
                ('sayfa_sayisi', models.IntegerField(blank=True, null=True)),
                ('yayin_tarihi', models.DateTimeField(blank=True, null=True)),
                ('tur', models.CharField(blank=True, max_length=15, null=True)),
                ('fiyat', models.IntegerField(blank=True, null=True)),
                ('stok', models.BooleanField(blank=True, null=True)),
                ('aciklama', models.TextField()),
                ('dil', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=50, null=True)),
                ('aciklama', models.TextField()),
            ],
        ),
    ]
